[theme]
base = "light"
primaryColor = "#00205B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FA"
textColor = "#182A3A"
font = "sans serif"

[server]
headless = true
runOnSave = false
maxUploadSize = 10
maxMessageSize = 50
enableCORS = true
enableXsrfProtection = true

[client]
showErrorDetails = "none"
toolbarMode = "viewer"

[runner]
magicEnabled = false

[browser]
gatherUsageStats = false
