[theme]
base = "light"
primaryColor = "#00205B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FA"
textColor = "#182A3A"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
